Pipelines WIP, added health check

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -137,3 +137,27 @@ jobs:
       - name: Release the App on Heroku
         run: |
           heroku restart --app ${{ secrets.HEROKU_APP_NAME }}
+
+      - name: Check Heroku App Status
+        run: |
+          heroku ps --app ${{ secrets.HEROKU_APP_NAME }} | grep "up"
+
+  health-check:
+    runs-on: ubuntu-latest
+    needs: deploy  # Run this job only if the deploy job succeeds
+
+    steps:
+      - name: Wait for App to Be Ready
+        run: |
+          echo "Waiting for app to be fully deployed..."
+          sleep 60  # Wait for 60 seconds to give the app time to start
+
+      - name: Health Check - Verify the Application is Running
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" https://rest-api-design-558f269d8e55.herokuapp.com/health)
+          if [ "$response" -ne 200 ]; then
+            echo "Health check failed! Response code: $response"
+            exit 1
+          else
+            echo "Health check passed with response code: $response"
+          fi
